# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61be4f50a2831c8cd96c0c2f21ce1b03db3cdb63c5e96c28dd69169332bde53876a675ee8ea7462e083f1eda0aa5bf3fdb9277193693ee58566653b3c1d5a186

test:
  secret_key_base: 54c7905ccb6784d7686f08d61a4b2d5ff417a9f644a9b18f46ae400990a333157b6dbbf5abcd8508298fbbbdd0d088ae5941ace7e0dcd01344d076b6e2a06982

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  new_relic_license: <%= ENV["NEW_RELIC_LICENSE"] %>
